### ISSUE TITLE
filemtime() в пути скрипта

### ISSUE THREAD

**Issue by abc-cms** [abc-cms/abc-cms#12]
сейчас обнаружил что filemtime() срабатывает для всех файлов в функции html_sources
получается просто так тратятся ресурсы
пока хорошего решения не нашел, просто фиксирую что нужно поправить

**Comment by quadrogod** [comment]
сделать как я говорил, хранить тип стиль - ссылка до файла
например 'index' => array(
'css' => '/.../file.css',
'js' => '/.../file.js'
),
потом непосредственно перед сборкой нужных добавлять filemtime для локальных файлов, что-то типа (!strpos($массив[ключ],"://"))

**Comment by quadrogod** [comment]
и вынести этот массив из функции в конфиги

**Comment by abc-cms** [comment]
вопрос закрываю
появилась функция html_sources
