### ISSUE TITLE
проблемы с кодировкой

### ISSUE THREAD

**Issue by Mo-** [abc-cms/abc-cms#13]
# например
https://github.com/abc-cms/abc-cms/blob/master/admin/actions/edit.php

**Comment by quadrogod** [comment]
проблема конкретно в редакторе с которым работает Дмитрий. Он по умолчанию сохраняет в ANSI, можно найти конвертеры (я раньше искал, как то нужно было) скармливаешь ему папки, он пройдет и изменит кодировку на установленую. 

Сам мучаюсь когда надо открыть какой либо файл с русскими комментами, приходится сначала через np++ конвертить

**Comment by abc-cms** [comment]
я по мере кодировку меняю
можешь просто сюда писать названия файлов - я их буду менять
как сделать массовую конвертацию не в курсе

**Comment by abc-cms** [comment]
закрыто
