### ISSUE TITLE
404

### ISSUE THREAD

**Issue by abc-cms** [abc-cms/abc-cms#14]
есть две проблемы со страницами 404
1. несуществующие урл должны всегда возвращать 404
например /novosti/1-novost/bla-bla/ должна возвращать 404 так как третьего уровня вложенности в новостях нет
этот вопрос решается так
<pre>//одна запись
if ($u[2]) {
	if ($u[3]=='' AND $news = mysql_select(..) {
		..
	}
	else $error++;
}
//список записей
else {
	..
}</pre>
2. вторая проблема - несуществующие $_GET запросы
так сейчас страница с урл /?porno=fuck вернет просто главную страницу 200
если подобные ссылки злоумышленник намеренно разместит в сети и они проиндексируются гуглом, то сайт может попасть под фильтры
такая практика уже довольно популярна
сейчас у нас есть
- пагинатор в новостях и в магазине
- фильтр поиска в каталоге
- удаление товара из корзины
- восстановление пароля
получается для каждого модуля, если в нем используются гет параметры, то нужно их перечислять в глобальной переменной
а в основном index.php смотреть, если используются неразрешенные гет параметры то возвращать 404 или другой какой-то код
но это не решит проблему, если в разрешенный гет параметр будет передано ложное значение, например /?brand=porno - ключ brand разрешен но его значение нет
вот тут пока не знаю что придумать, чтобы это сильно не усложняло код
получается так же нужно придумать способ для обработки значений параметров гет, и если они ложные то предпринимать соотвествующие действия

**Comment by quadrogod** [comment]
думаю вместо $error++ лушче сделать вывод страницы шаблона типа /common/error_404 и die()

**Comment by abc-cms** [comment]
может сделать функцию типа error($code), куда передавать код ошибки и уже внутри этой функции можно делать die и подключать нужные шаблоны
засунуть её наверно в common_func
её же можно вызывать при ошибке подключения к БД

**Comment by abc-cms** [comment]
проблема решена с помощью доп условий в каждом модуле, например
if ($u[3]) $error++;
else {
...
}
