### ISSUE TITLE
в .htaccess что то перемудрено

### ISSUE THREAD

**Issue by Mo-** [abc-cms/abc-cms#22]
в .htaccess что то перемудрено! как минимум не гарантируется работа. например на beget не работает абсолютно. советую посмотреть настройки в html5 boilerplate там собраны лучшие практики от перцев индустрии.

**Comment by d-u-a-l** [comment]
Там что-то не так в блоке <IfModule mod_filter.c>. У меня все завелось, когда поменял на
<IfModule mod_filter.c>
		AddOutputFilterByType DEFLATE "application/atom+xml" "application/javascript" "application/json" "application/ld+json" "application/manifest+json" "application/rdf+xml"
		AddOutputFilterByType DEFLATE "application/rss+xml" "application/schema+json" "application/vnd.geo+json" "application/vnd.ms-fontobject" "application/x-font-ttf"
		AddOutputFilterByType DEFLATE "application/x-javascript" "application/x-web-app-manifest+json" "application/xhtml+xml" "application/xml" "font/eot"
		AddOutputFilterByType DEFLATE "font/opentype" "image/bmp" "image/svg+xml" "image/vnd.microsoft.icon" "image/x-icon" "text/cache-manifest" "text/css"
		AddOutputFilterByType DEFLATE "text/html" "text/javascript" "text/plain" "text/vcard" "text/vnd.rim.location.xloc" "text/vtt" "text/x-component"
		AddOutputFilterByType DEFLATE "text/x-cross-domain-policy" "text/xml"
	</IfModule>
Можно использовать только одну директиву AddOutputFilterByType, разбил, что-бы помещалось на экран

**Comment by Mo-** [comment]
заменил все, кроме рерайта кусками из бойлерплэйта
