### ISSUE TITLE
правка прав доступа

### ISSUE THREAD

**Issue by quadrogod** [abc-cms/abc-cms#24]
user_types.php 7 строкой добавить код
if ($user['type'] == $get['id']){
            $_SESSION['user']['access_admin'] = $post['access_admin'];            
        }
я так и не понял, что там может сломаться когда объяснял это в скайпе, удачно без проишествий использую на всех последних задачах, тем более переписывается для контретного пользователя, непосредственно работающего с админкой.

**Comment by abc-cms** [comment]
счас это так решается
//переавторизация если меняем права доступа
function after_save() {
	global $user,$get;
	if ($user['type']==$get['id']) {
		$user = user('re-auth');
	}
}
