### ISSUE TITLE
Не работает тинумайс

### ISSUE THREAD

**Issue by Elgernon** [abc-cms/abc-cms#25]
В новой версии цмс, той что сейчас выложена. Те таблицы в админке, в которых используется тинумайс не сохраняются, а сам тинумайс не отображается, а выводится как текстареа

**Comment by d-u-a-l** [comment]
Я уже ругался матом по этому поводу. Там, где он подключается, кто-то перенес строку не на свое место, в итоге при загрузке формы скрипт парсится с ошибкой

**Comment by d-u-a-l** [comment]
fixed

**Comment by quadrogod** [comment]
Дима менял 12 дней назад что-то в том направлении.
Вообще надо сделать ветку мастер и ветку девеп, и пусть Дмитрий утверждает коммиты в мастер. От ошибок все равно не избавит, но это будет правильней.
