### ISSUE TITLE
простейшее сжатие HTML перед выводом

### ISSUE THREAD

**Issue by Mo-** [abc-cms/abc-cms#29]
<?php
// Сжатие HTML
ob_start();

/*
/     тут магия
*/

// Сжатие HTML
$out = ob_get_clean();
$out = preg_replace('/(?![^<]*<\/pre>)[\n\r\t]+/', "\n", $out);
$out = preg_replace('/ {2,}/', ' ', $out);
$out = preg_replace('/>[\n]+/', '>', $out);
echo $out;

**Comment by quadrogod** [comment]
вот так лучше, функцию в коммоны, а ob_start в любое место индексного файла. где подстмотренно не помню, недавно делал

function sanitize_output($buffer) {
    $search = array(
        '/\>[^\S ]+/s',  // strip whitespaces after tags, except space
        '/[^\S ]+\</s',  // strip whitespaces before tags, except space
        '/(\s)+/s'       // shorten multiple whitespace sequences
    );
    $replace = array(
        '>',
        '<',
        '\\1'
    );
    $buffer = preg_replace($search, $replace, $buffer);
    return $buffer;
}

ob_start("sanitize_output");

**Comment by d-u-a-l** [comment]
объясни теперь - зачем? что-бы сложнее было исходный код читать в браузере? Так в инструментах разработчика он форматируется красиво в любом случае. Или пропускную способность экономить? Много не сэкономишь, тем более, для этого есть gzip, а нагрузка на сервер увеличится

**Comment by quadrogod** [comment]
ну, есть клиенты "дрочеры" которым важны циферки в гугле https://developers.google.com/speed/pagespeed/insights/ а это одна из рекомендаций.
Потому там приходится и html ужимать и картинки сотронними сервисами пережимать и т.д.
вообще можно просто галку в админку добавить и по моему примеру включать и отключать ужатие. Прегреплейсы работают быстро и на процессорную скорость это вообще никак не повлияет. А читать код можно тем же фаирбагом, он строит as is dom документ.

**Comment by abc-cms** [comment]
v.1.1.8 - html_minify
