### ISSUE TITLE
отвязать капчу от jquery

### ISSUE THREAD

**Issue by Mo-** [abc-cms/abc-cms#35]
отвязать капчу от jquery

**Comment by quadrogod** [comment]
зачем? я просто выношу в коммон на window.onload получение, он все равно после вызывается, а в форме класс добавляю

**Comment by Mo-** [comment]
идеально!

2016-03-17 12:45 GMT+06:00 quadrogod <notifications@github.com>:

> зачем? я просто выношу в коммон на window.onload получение, он все равно
> после вызывается, а в форме класс добавляю
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/abc-cms/abc-cms/issues/35#issuecomment-197731096>
>



-- 
С уважением Дмитрий!
