### ISSUE TITLE
Заменить тип поля для доступа к модулям

### ISSUE THREAD

**Issue by quadrogod** [abc-cms/abc-cms#42]
Уже не первый раз спотыкаюсь, в админке на user_types.access_admin стоит varchar 1000
чуть больше модулей добавляем и ломается всё. Пусть по умолчанию TEXT стоит, от этого нечего не изменится в плане производительности, зато сэкономит кучу нервов.

ALTER TABLE `user_types` CHANGE `access_admin` `access_admin` TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL DEFAULT NULL

**Comment by abc-cms** [comment]
сделано
