### ISSUE TITLE
переключение вкладок в форме

### ISSUE THREAD

**Issue by Mo-** [abc-cms/abc-cms#48]
при изменении на одной из вкладок и перехоже на другую вкладку выводится алерт с сообщением о том, что форма изменена и действительно ли я хочу перейти по ссылке.....

**Comment by abc-cms** [comment]
не вижу такой проблемы, напиши последовательность действий при которых так происходит и какой браузер

**Comment by Mo-** [comment]
уже не вижу этого. возможно уже не актуально
